# Generated by Django 5.0.6 on 2024-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1024)),
                ('precio', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=1024)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('oferta', models.BooleanField(default=False)),
            ],
        ),
    ]
