# Generated by Django 5.0.6 on 2024-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_tipoproducto_cliente_carrito_producto_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='oferta',
            new_name='es_oferta',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
