# Generated by Django 5.0.6 on 2024-06-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_rename_oferta_producto_es_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
    ]
