# Generated by Django 5.0.6 on 2024-06-29 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_remove_cliente_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mi_aplicacion.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto')),
            ],
        ),
    ]
