# Generated by Django 5.0.6 on 2024-06-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_remove_carrito_fecha_creacion_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
