# Generated by Django 5.0.6 on 2024-06-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_alter_carrito_id_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='producto',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
