# Generated by Django 5.0.6 on 2024-07-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_remove_cliente_telefono_producto_es_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='appaterno',
            field=models.CharField(default='ApellidoDesconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='pnombre',
            field=models.CharField(default='ApellidoDesconocido', max_length=255),
            preserve_default=False,
        ),
    ]
