# Generated by Django 5.0.6 on 2024-07-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_cliente_appaterno_cliente_pnombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
